/**
 * TOTP 2FA + backup codes — 00 FR-3/FR-5, AC-2/3/5.
 *
 * The clock is injected on every verification (design.md § Edge cases) so
 * lockout and skew behaviour are deterministic in tests rather than dependent
 * on when CI happens to run.
 */
import { createHash, randomInt } from "node:crypto";
import { authenticator } from "otplib";

/** RFC 6238 default. */
export const TOTP_STEP_SECONDS = 30;

/**
 * Accept the previous and next step as well as the current one.
 * design.md: "Clock skew for TOTP → allow ±1 step window." Wider would weaken
 * the factor; narrower rejects users whose phone clock drifts by seconds.
 */
export const TOTP_WINDOW = 1;

const BACKUP_CODE_LENGTH = 10;
/** Crockford-ish base32: no I/L/O/U, so codes can't be misread off a screen. */
const BACKUP_ALPHABET = "ABCDEFGHJKMNPQRSTVWXYZ23456789";

export function generateTotpSecret(): string {
  return authenticator.generateSecret();
}

/**
 * Verify a submitted code against the secret at a given instant.
 *
 * `at` defaults to now for production callers; tests pass a fixed instant.
 * Never throws — malformed input is simply "not valid".
 */
export function verifyTotp(secret: string, token: string, at: Date = new Date()): boolean {
  const candidate = token.replace(/\s/g, "");
  if (!/^\d{6}$/.test(candidate)) return false;

  try {
    authenticator.options = {
      epoch: at.getTime(),
      step: TOTP_STEP_SECONDS,
      window: TOTP_WINDOW,
    };
    return authenticator.check(candidate, secret);
  } catch {
    return false;
  } finally {
    // otplib's options are module-global; leaving them set would make the next
    // verification in this process use a stale injected clock.
    authenticator.resetOptions();
  }
}

/** The `otpauth://` URI an authenticator app consumes as a QR code (AC-5). */
export function buildOtpAuthUrl(params: {
  secret: string;
  accountName: string;
  issuer?: string;
}): string {
  const issuer = params.issuer ?? "Woodpecker PMS";
  return authenticator.keyuri(params.accountName, issuer, params.secret);
}

/**
 * One-time recovery codes, shown once at enrolment and stored only as hashes
 * (FR-5). Uses `randomInt` (CSPRNG) — `Math.random` would make them guessable.
 */
export function generateBackupCodes(count = 10): string[] {
  const codes = new Set<string>();
  while (codes.size < count) {
    let code = "";
    for (let i = 0; i < BACKUP_CODE_LENGTH; i++) {
      code += BACKUP_ALPHABET[randomInt(BACKUP_ALPHABET.length)];
    }
    codes.add(code);
  }
  return [...codes];
}

/**
 * Hash a backup code for storage/comparison.
 *
 * Plain SHA-256 rather than bcrypt is deliberate and safe here: unlike a
 * human-chosen password, a backup code is 10 random chars from a 30-symbol
 * alphabet (~49 bits) generated by us, so there is no dictionary to attack and
 * no need for a slow KDF. Normalised first so case/spacing/dashes as typed by
 * the user still match.
 */
export function hashBackupCode(code: string): string {
  const normalized = code.replace(/[\s-]/g, "").toUpperCase();
  return createHash("sha256").update(normalized).digest("hex");
}

export type ConsumeBackupCodeResult = {
  consumed: boolean;
  /** The set to persist back to `User.backupCodes`. */
  remainingHashes: string[];
};

/**
 * Match a presented code against the stored hashes and remove it (AC-3:
 * single-use). Pure: it returns the new set rather than mutating, so the caller
 * decides the transaction boundary — the actual consume must happen under a row
 * lock (design.md § Edge cases: "Race on backup-code reuse → consume
 * atomically").
 */
export function consumeBackupCode(
  presented: string,
  storedHashes: readonly string[],
): ConsumeBackupCodeResult {
  const candidate = hashBackupCode(presented);
  const index = storedHashes.indexOf(candidate);
  if (index === -1) return { consumed: false, remainingHashes: [...storedHashes] };

  const remaining = [...storedHashes];
  remaining.splice(index, 1);
  return { consumed: true, remainingHashes: remaining };
}
