import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "coverage/**",
      "prisma/migrations/**",
      // Generated by Next on every build; its triple-slash reference is not ours to fix.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // coding-standards.md: no `any`; narrow from `unknown` instead.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // 00-platform T-8 / FR-8: operational reads and writes go through
    // db.scoped(user) or db.activeProperty(user). Importing the raw Prisma
    // client outside lib/db (or the vetted escape hatches) is a scope leak.
    files: ["src/features/**/*.ts", "src/features/**/*.tsx", "src/app/**/*.ts", "src/app/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/db/client",
              importNames: ["prisma"],
              message:
                "Use db.scoped(user) / db.activeProperty(user) from @/lib/db — raw unscoped Prisma access breaks property tenancy (00 FR-8). Reporting rollups must use db.unscoped() with an explicit justification.",
            },
          ],
        },
      ],
    },
  },
  {
    // 17 T-9 / mobile-first.md: base styles target the SMALLEST viewport and
    // enhance upward with min-width variants (sm:, md:, …). A `max-*:` breakpoint
    // variant is desktop-first — a layout fixed downward instead of built up.
    // (This flags the max-WIDTH BREAKPOINT variant `max-md:`; the `max-w-*` sizing
    // utility is unaffected — the breakpoint name + colon is what matches.)
    files: ["src/**/*.tsx"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/max-(sm|md|lg|xl|2xl):/]",
          message:
            "Desktop-first breakpoint (max-*:). Style the base (smallest) viewport by default and enhance upward with min-width variants (sm:, md:). See mobile-first.md.",
        },
        {
          selector: "TemplateElement[value.cooked=/max-(sm|md|lg|xl|2xl):/]",
          message:
            "Desktop-first breakpoint (max-*:). Style the base (smallest) viewport by default and enhance upward with min-width variants (sm:, md:). See mobile-first.md.",
        },
      ],
    },
  },
];

export default config;
