import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "coverage/**",
      "prisma/migrations/**",
      // Generated by Next on every build; its triple-slash reference is not ours to fix.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // coding-standards.md: no `any`; narrow from `unknown` instead.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // 00-platform T-8 / FR-8: operational reads and writes go through
    // db.scoped(user) or db.activeProperty(user). Importing the raw Prisma
    // client outside lib/db (or the vetted escape hatches) is a scope leak.
    files: ["src/features/**/*.ts", "src/features/**/*.tsx", "src/app/**/*.ts", "src/app/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/db/client",
              importNames: ["prisma"],
              message:
                "Use db.scoped(user) / db.activeProperty(user) from @/lib/db — raw unscoped Prisma access breaks property tenancy (00 FR-8). Reporting rollups must use db.unscoped() with an explicit justification.",
            },
          ],
        },
      ],
    },
  },
];

export default config;
