/**
 * 21 · Payroll — T-2 seed fixtures.
 *
 * specs/21-payroll/user-stories.md § Test Fixtures (MONTH = 2026-07):
 *   S-ANU  — ₹31,000/mo, joined 2025-01-01, active. Attendance: 600 OT minutes,
 *            2 UNPAID days + 1 SICK day (ATT-OT + ATT-UNPAID). Outstanding
 *            advance ₹40,000 (ADV-ANU).
 *   S-LATE — ₹31,000/mo, joined 2026-07-16 (mid-month).
 *   S-EX   — left (deletedAt 2026-06-30) → excluded from the run.
 *
 * Idempotent: fixed ids + upserts, matching every other seed module. Does NOT
 * create a PayrollRun — the run is generated by the action under test.
 */
import type { PrismaClient } from "@prisma/client";
import { PROP_A_ID } from "./fixtures";

export const STAFF_ANU_ID = "staff_wmg_anu";
export const STAFF_LATE_ID = "staff_wmg_late";
export const STAFF_EX_ID = "staff_wmg_ex";
export const ADVANCE_ANU_ID = "adv_wmg_anu";

const SALARY = 3_100_000; // ₹31,000 in paise
const D = (iso: string) => new Date(`${iso}T00:00:00.000Z`); // @db.Date UTC midnight

export async function seedPayroll(prisma: PrismaClient): Promise<void> {
  await prisma.staff.upsert({
    where: { id: STAFF_ANU_ID },
    create: { id: STAFF_ANU_ID, propertyId: PROP_A_ID, name: "Anu Kumar", mobile: "9800100001", department: "Front Office", monthlySalaryPaise: SALARY, joinedOn: D("2025-01-01"), isActive: true },
    update: { monthlySalaryPaise: SALARY, joinedOn: D("2025-01-01"), leftOn: null, isActive: true, deletedAt: null },
  });
  await prisma.staff.upsert({
    where: { id: STAFF_LATE_ID },
    create: { id: STAFF_LATE_ID, propertyId: PROP_A_ID, name: "Late Joiner", mobile: "9800100002", department: "Housekeeping", monthlySalaryPaise: SALARY, joinedOn: D("2026-07-16"), isActive: true },
    update: { monthlySalaryPaise: SALARY, joinedOn: D("2026-07-16"), leftOn: null, isActive: true, deletedAt: null },
  });
  await prisma.staff.upsert({
    where: { id: STAFF_EX_ID },
    create: { id: STAFF_EX_ID, propertyId: PROP_A_ID, name: "Ex Employee", mobile: "9800100003", department: "Kitchen", monthlySalaryPaise: SALARY, joinedOn: D("2024-01-01"), leftOn: D("2026-06-30"), isActive: false, deletedAt: D("2026-06-30") },
    update: { leftOn: D("2026-06-30"), isActive: false, deletedAt: D("2026-06-30") },
  });

  // ATT-UNPAID (2 UNPAID + 1 SICK) + ATT-OT (600 OT minutes) for S-ANU.
  const days: { day: string; leaveType: "NONE" | "SICK" | "UNPAID"; isLeave: boolean; overtimeMinutes: number; workedMinutes: number | null }[] = [
    { day: "2026-07-05", leaveType: "UNPAID", isLeave: true, overtimeMinutes: 0, workedMinutes: null },
    { day: "2026-07-06", leaveType: "UNPAID", isLeave: true, overtimeMinutes: 0, workedMinutes: null },
    { day: "2026-07-07", leaveType: "SICK", isLeave: true, overtimeMinutes: 0, workedMinutes: null },
    { day: "2026-07-10", leaveType: "NONE", isLeave: false, overtimeMinutes: 300, workedMinutes: 480 },
    { day: "2026-07-11", leaveType: "NONE", isLeave: false, overtimeMinutes: 300, workedMinutes: 480 },
  ];
  for (const d of days) {
    await prisma.attendance.upsert({
      where: { staffId_day: { staffId: STAFF_ANU_ID, day: D(d.day) } },
      create: { staffId: STAFF_ANU_ID, day: D(d.day), leaveType: d.leaveType, isLeave: d.isLeave, overtimeMinutes: d.overtimeMinutes, workedMinutes: d.workedMinutes },
      update: { leaveType: d.leaveType, isLeave: d.isLeave, overtimeMinutes: d.overtimeMinutes, workedMinutes: d.workedMinutes },
    });
  }

  // ADV-ANU — ₹40,000 outstanding (recoveredPaise 0).
  await prisma.staffAdvance.upsert({
    where: { id: ADVANCE_ANU_ID },
    create: { id: ADVANCE_ANU_ID, staffId: STAFF_ANU_ID, amountPaise: 4_000_000, recoveredPaise: 0, note: "Festival advance" },
    update: { amountPaise: 4_000_000, recoveredPaise: 0 },
  });
}
